/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
} from "@alephium/web3";
import { default as FeeCollectorContractJson } from "../FeeCollector.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace FeeCollectorTypes {
  export type State = Omit<ContractState<any>, "fields">;
}

class Factory extends ContractFactory<FeeCollectorInstance, {}> {
  at(address: string): FeeCollectorInstance {
    return new FeeCollectorInstance(address);
  }

  tests = {
    collectFee: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          never,
          {
            from1: Address;
            tokenId1: HexString;
            amount1: bigint;
            from2: Address;
            tokenId2: HexString;
            amount2: bigint;
          }
        >,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "collectFee", params);
    },
  };
}

// Use this object to test and deploy the contract
export const FeeCollector = new Factory(
  Contract.fromJson(
    FeeCollectorContractJson,
    "",
    "3424e7f6dcfba905d0e7fc87e1aadef66678ece6696b9e341bb31c3097134cdb"
  )
);

// Use this class to interact with the blockchain
export class FeeCollectorInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FeeCollectorTypes.State> {
    return fetchContractState(FeeCollector, this);
  }
}
