/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as DepositScriptJson } from "../Deposit.ral.json";
import { default as TransferScriptJson } from "../Transfer.ral.json";

export const Deposit = new ExecutableScript<{
  contract: HexString;
  tokenId: HexString;
  amount: bigint;
}>(Script.fromJson(DepositScriptJson, ""));

export const Transfer = new ExecutableScript<{
  contract: HexString;
  firstTokenId: HexString;
  totalSellerFee: bigint;
  secondTokenId: HexString;
  totalBuyerFee: bigint;
}>(Script.fromJson(TransferScriptJson, ""));
